# Generated by Django 2.0.5 on 2018-11-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepad_mail', '0002_ticket_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='GUID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='ID')),
                ('event_id', models.IntegerField(verbose_name='ID мероприятия')),
                ('status', models.CharField(choices=[('n', 'новый'), ('p', 'оплачено'), ('c', 'отказ'), ('1', 'напоминание 1'), ('2', 'напоминание 2'), ('3', 'напоминание 3')], default='n', max_length=1, verbose_name='статус')),
                ('reg_date', models.DateTimeField(verbose_name='создан')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='имя')),
                ('surname', models.CharField(blank=True, max_length=32, verbose_name='фамилия')),
                ('payment_amount', models.IntegerField(verbose_name='сумма')),
                ('pay_link', models.URLField(max_length=128, verbose_name='ссылка на оплату')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id', 'event_id'], name='unique_index'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'reg_date'], name='expiration_index'),
        ),
    ]
